# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 17:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('show_my_email', models.BooleanField(default=True)),
                ('description', models.TextField(default='Local business')),
            ],
        ),
        migrations.CreateModel(
            name='Neighbourhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('display', models.ImageField(default='groups/group.png', upload_to='groups/')),
                ('description', models.TextField(default='Random group')),
                ('police', models.TextField(default='999')),
                ('health', models.TextField(default='213')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.TextField()),
                ('neighbourhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='neighbourhood.Neighbourhood')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='career',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='dp',
        ),
        migrations.AddField(
            model_name='profile',
            name='Name',
            field=models.TextField(default='Anonymous'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default="I'm using hoodwatch"),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='users/user.png', upload_to='users/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbourhood.Profile'),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hoods', to='neighbourhood.Profile'),
        ),
        migrations.AddField(
            model_name='business',
            name='neighbourhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biashara', to='neighbourhood.Neighbourhood'),
        ),
        migrations.AddField(
            model_name='business',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbourhood.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='neighbourhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='people', to='neighbourhood.Neighbourhood'),
        ),
    ]
